source("R/fct_get_recipes.R")
source("R/fct_create_week.R")
source("R/fct_generate_screen.R")
source("R/fct_create_menu_week.R")
source("R/fct_get_choices_user.R")
source("R/fct_get_ingredient_list.R")
